
DROP TYPE IF EXISTS Region CASCADE;
CREATE TYPE Region AS ENUM('NORTH_AMERICA', 'EUROPE', 'ASIA');

DROP TYPE IF EXISTS OrderStatus CASCADE;
CREATE TYPE OrderStatus AS ENUM('NEW', 'SCHEDULED', 'REJECTED', 'ONGOING', 'DONE');

DROP TABLE IF EXISTS Orders;
CREATE TABLE Orders (
	id SERIAL PRIMARY KEY,
	email VARCHAR(256) NOT NULL,
	target_url VARCHAR(256) NOT NULL,
	region Region NOT NULL,
	num_nodes INT NOT NULL,
	duration REAL NOT NULL,
	status OrderStatus NOT NULL DEFAULT 'NEW'
);
